// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvwvkbovdpnivwbwnwys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2d3ZrYm92ZHBuaXZ3Yndud3lzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTc2ODMsImV4cCI6MjA2OTI5MzY4M30.TTgFJ-F36zmWKXe7wLamcR_gBCHHBvub_Bd6dnJOpsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});